export const tvSettings = {
  enableScrollChannelChange: false,
  autoPlayNextEpisode: true,
  volumeStep: 5,
  volumeMin: 0,
  volumeMax: 100,
  defaultVolume: 50,
  channelOsdHideMs: 2000,
  episodeOsdHideMs: 2000,
  volumeOsdHideMs: 1500,
  channelTransitionMs: 150,
  powerOnDurationMs: 450,
  powerOffDurationMs: 450,
  channelChangeLockMs: 250,
  maxEpisodeTitleLength: 28,
  loadDurationMs: 1200,
  loadPlayAtProgress: 0,
  loadVolumeFadeAtProgress: 6 / 7,
  loadVolumeFadeMs: 200,
  loadMaxExtendMs: 1500,
  shieldRevealDelayMs: 80,
  playbackStartTimeoutMs: 4500,
} as const;
