export const tvSettings = {
  enableScrollChannelChange: false,
  autoPlayNextEpisode: true,
  volumeStep: 5,
  volumeMin: 0,
  volumeMax: 100,
  defaultVolume: 50,
  channelOsdHideMs: 2000,
  episodeOsdHideMs: 2000,
  volumeOsdHideMs: 1500,
  channelTransitionMs: 250,
  powerOnDurationMs: 600,
  powerOffDurationMs: 450,
  channelChangeLockMs: 300,
  maxEpisodeTitleLength: 28,
  tuneInMinMs: 2200,
  tuneInSettleMs: 500,
  tuneInMaxMs: 8000,
} as const;
